run:
    tests: true

linters-settings:
    gofmt:
        simplify: true
    goimports:
        local-prefixes: github.com/gohornet,github.com/iotaledger
    golint:
        min-confidence: 0.9
    gocyclo:
        min-complexity: 15
    govet:
        check-shadowing: false
    misspell:
        locale: US

linters:
    enable:
        - misspell
        - gofmt
        - goimports
        - govet
    disable:
        - errcheck
        - gochecknoglobals
        - golint
