# Documentation at http://goreleaser.com

# Project name
project_name: HORNET

# Environment variables
env:
  - GO111MODULE=on

# Builds
builds:
  # Linux AMD64
  - id: hornet-linux-amd64
    binary: hornet
    flags:
      - -tags=rocksdb
    ldflags:
      - -s -w -X github.com/iotaledger/hornet/core/cli.AppVersion={{.Version}}
    main: main.go
    goos:
      - linux
    goarch:
      - amd64
  # Linux ARM64
  - id: hornet-linux-arm64
    binary: hornet
    flags:
      - -tags=rocksdb
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      - -s -w -X github.com/iotaledger/hornet/core/cli.AppVersion={{.Version}}
    main: main.go
    goos:
      - linux
    goarch:
      - arm64
  ## Windows AMD64
  #- id: hornet-windows-amd64
  #  binary: hornet
  #  flags:
  #    - -tags=rocksdb
  #  env:
  #    - CGO_ENABLED=1
  #    - CC=/usr/bin/x86_64-w64-mingw32-gcc-posix
  #    - CXX=/usr/bin/x86_64-w64-mingw32-g++-posix
  #  ldflags:
  #    - -s -w -X github.com/iotaledger/hornet/core/cli.AppVersion={{.Version}}
  #  main: main.go
  #  goos:
  #    - windows
  #  goarch:
  #    - amd64

# Archives
archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}-{{.Version}}_{{.Os}}_{{.Arch}}"
    replacements:
      amd64: x86_64
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
    files:
      - README.md
      - LICENSE
      - config_template.json
      - peering.json
      - profiles.json

# Checksum
checksum:
  name_template: "checksums.txt"

# Snapshot
snapshot:
  name_template: "{{ .Tag }}"

# Changelog
changelog:
  skip: true

announce:
  skip: "{{ if .Prerelease }}true{{ end }}"
  twitter:
    enabled: true
    message_template: "{{.ProjectName}}-{{.Version}} is out! Find all details at {{ .ReleaseURL }}! #IOTA #HORNET"

# Release
release:
  prerelease: auto
  name_template: "{{.ProjectName}}-{{.Version}}"
  github:
    owner: iotaledger
    name: hornet
