# Documentation at http://goreleaser.com

# Project name
project_name: HORNET

# Environment variables
env:
  - GO111MODULE=on

# Builds
builds:
  # Linux AMD64
  - id: hornet-linux-amd64
    binary: hornet
    flags:
      - -tags=builtin_static,rocksdb
    ldflags:
      - -s -w -X github.com/gohornet/hornet/core/cli.AppVersion={{.Version}}
    main: main.go
    goos:
      - linux
    goarch:
      - amd64
  # Linux ARM64
  - id: hornet-linux-arm64
    binary: hornet
    flags:
      - -tags=builtin_static,rocksdb
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      - -s -w -X github.com/gohornet/hornet/core/cli.AppVersion={{.Version}}
    main: main.go
    goos:
      - linux
    goarch:
      - arm64
  # Windows AMD64
  - id: hornet-windows-amd64
    binary: hornet
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    ldflags:
      - -s -w -X github.com/gohornet/hornet/core/cli.AppVersion={{.Version}}
    main: main.go
    goos:
      - windows
    goarch:
      - amd64

# Docker
dockers:
  # Docker AMD64
  - goos: linux
    goarch: amd64
    image_templates:
      - "gohornet/hornet:latest"
      - "gohornet/hornet:{{ .Tag }}"
    ids:
      - hornet
    dockerfile: docker/Dockerfile
    skip_push: auto

# Archives
archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}-{{.Version}}_{{.Os}}_{{.Arch}}"
    replacements:
      amd64: x86_64
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
    files:
      - README.md
      - LICENSE
      - config.json
      - peering.json
      - profiles.json

# DEB and RPM packages
nfpms:
  - id: nfpm
    package_name: hornet
    file_name_template: '{{ tolower .ProjectName }}_{{ replace .Version "v" "" }}_{{ .Arch }}'
    vendor: GoReleaser
    license: Apache 2.0
    maintainer: GoHORNET
    homepage: https://github.com/gohornet/hornet
    description: HORNET is a powerful IOTA fullnode software.
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: "nfpm/shared_files/hornet.service"
        dst: "/lib/systemd/system/hornet.service"

      - src: "config.json"
        dst: "/var/lib/hornet/config.json"
        type: config

      - src: "peering.json"
        dst: "/var/lib/hornet/peering.json"
        type: config

      - src: "profiles.json"
        dst: "/var/lib/hornet/profiles.json"
        type: config

      - src: "nfpm/shared_files/hornet.env"
        dst: "/etc/default/hornet"
        type: config

    dependencies:
      - systemd
      - wget
      - bash
    scripts:
      preremove: "nfpm/deb_files/prerm"
      postremove: "nfpm/deb_files/postrm"
      preinstall: "nfpm/deb_files/preinst"
      postinstall: "nfpm/deb_files/postinst"
    overrides:
      rpm:
        replacements:
          amd64: x86_64
        file_name_template: "{{ tolower .ProjectName }}-{{ .Version }}-{{ .Arch }}"
        scripts:
          preinstall: "nfpm/rpm_files/preinst"
          postinstall: "nfpm/rpm_files/postinst"
          preremove: "nfpm/rpm_files/prerm"
          postremove: "nfpm/rpm_files/postrm"

# Checksum
checksum:
  name_template: "checksums.txt"

# Snapshot
snapshot:
  name_template: "{{ .Tag }}"

# Changelog
changelog:
  skip: true

# Release
release:
  prerelease: auto
  name_template: "{{.ProjectName}}-{{.Version}}"
  github:
    owner: gohornet
    name: hornet
