#!/bin/sh
set -e
OPTS=""

if [ -n "$D" ]; then
    OPTS="--root=$D"
fi

if type systemctl >/dev/null 2>/dev/null; then
	if [ -z "$D" ]; then
		systemctl daemon-reload
	fi

        # if iota group doesn't exist, create it
        if [ ! $(getent group iota) ]; then
                groupadd iota > /dev/null
        fi   

	# if beekeeper user doesn't exist, create it
	if [ ! $(getent passwd beekeeper) ]; then
		useradd --no-create-home --system -g iota beekeeper > /dev/null
	fi

	mkdir -p /var/lib/hornet/db
	mkdir -p /var/lib/hornet/snapshot
	chmod -R 775 /var/lib/hornet
	chmod -R 775 /etc/hornet
	chown -R beekeeper:iota /var/lib/hornet
	chown -R beekeeper:iota /etc/hornet

	systemctl $OPTS disable hornet.service

	if [ -z "$D" -a "disable" = "enable" ]; then
		systemctl --no-block restart hornet.service
	fi
fi
