#!/bin/sh
set -e

case "$1" in
configure)

	chown -R hornet-legacy:hornet-legacy /var/lib/hornet-legacy

	if type systemctl >/dev/null 2>/dev/null; then
		systemctl daemon-reload

		# Only restart if the HORNET service is enabled
		if systemctl is-enabled -q hornet-legacy.service; then
			systemctl --no-block restart hornet-legacy.service
		fi

	fi
	;;

abort-upgrade | abort-remove | abort-deconfigure) ;;

*)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
