#!/bin/sh

set -e

case "$1" in
remove)
    # Remove directories (database)
    rm -rf /var/lib/hornet/*/
    ;;
purge)
    # Remove config files
    rm -rf /var/lib/hornet
    if id hornet >/dev/null 2>&1; then
        deluser hornet >/dev/null
    fi
    ;;
upgrade | failed-upgrade | abort-install | abort-upgrade | disappear) ;;

*)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac
