#!/bin/sh

set -e

case "$1" in
install)
    # if hornet user doesn't exist, create it
    if ! id hornet-legacy >/dev/null 2>&1; then
        useradd --no-create-home --system hornet-legacy >/dev/null
    fi
    mkdir -p /var/lib/hornet-legacy
    echo "WARNING: The autopeering plugin will disclose your public IP address to possibly all nodes and entry points. Please disable the plugin prior to the first start if you do not want this to happen!"
    ;;

upgrade)
    echo "Stopping HORNET-legacy. This may take a while..."
    systemctl stop hornet-legacy.service
    echo "HORNET-legacy stopped, start update..."
    ;;

abort-upgrade) ;;

*)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
