#!/bin/sh

set -e

backup_files() {
    echo "Creating backup, this may take some time..."
    mkdir -p /var/lib/hornet_backup
    mv /var/lib/hornet/* /var/lib/hornet_backup
    echo "Backup done, you can find your old files in /var/lib/hornet_backup"
}

case "$1" in
install)
    # if hornet user doesn't exist, create it
    if ! id hornet >/dev/null 2>&1; then
        useradd --no-create-home --system hornet >/dev/null
    fi
    mkdir -p /var/lib/hornet
    ;;

upgrade)
    echo "Stopping HORNET. This may take a while..."
    systemctl stop hornet.service
    echo "HORNET stopped, start update..."

    if echo "$2" | grep -qP '0\.[\d]+\.[\d]+' >/dev/null; then
        # legacy version installed, ask if user wants to backup old data
        echo "You are going to upgrade HORNET to the new Chrysalis version."
        echo "This is a breaking change. The old database files are incompatible."
        read -r -p "Do you want to backup your old files? [Y/n] " input

        case $input in
        [yY][eE][sS] | [yY])
            backup_files
            ;;
        [nN][oO] | [nN])
            echo "Removing old files, this may take some time..."
            rm -rf /var/lib/hornet/*/
            ;;
        *)
            backup_files
            ;;
        esac

    fi
    ;;

abort-upgrade) ;;

*)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
