#!/bin/sh

set -e

case "$1" in
remove)
	if type systemctl >/dev/null 2>/dev/null; then
		systemctl stop hornet-legacy.service
		if systemctl is-enabled -q hornet-legacy.service; then
			systemctl disable hornet-legacy.service >/dev/null 2>/dev/null
		fi
	fi
	;;

failed-upgrade | deconfigure | upgrade) ;;

*)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
