#!/bin/sh

set -e

SERVICE_NAME="hornet"
SYSTEMD_SERVICE="${SERVICE_NAME}.service"

case "$1" in
    remove)
        deb-systemd-invoke stop "${SYSTEMD_SERVICE}" >/dev/null
    ;;
    upgrade|deconfigure|failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

