// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: inx.proto

package inx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageFilter) Reset() {
	*x = MessageFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFilter) ProtoMessage() {}

func (x *MessageFilter) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFilter.ProtoReflect.Descriptor instead.
func (*MessageFilter) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{0}
}

type SubmitMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *WrappedMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SubmitMessageRequest) Reset() {
	*x = SubmitMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageRequest) ProtoMessage() {}

func (x *SubmitMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageRequest.ProtoReflect.Descriptor instead.
func (*SubmitMessageRequest) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitMessageRequest) GetMessage() *WrappedMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type SubmitMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId []byte `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
}

func (x *SubmitMessageResponse) Reset() {
	*x = SubmitMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageResponse) ProtoMessage() {}

func (x *SubmitMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageResponse.ProtoReflect.Descriptor instead.
func (*SubmitMessageResponse) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitMessageResponse) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type StreamedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId []byte          `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Message   *WrappedMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StreamedMessage) Reset() {
	*x = StreamedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamedMessage) ProtoMessage() {}

func (x *StreamedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamedMessage.ProtoReflect.Descriptor instead.
func (*StreamedMessage) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{3}
}

func (x *StreamedMessage) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *StreamedMessage) GetMessage() *WrappedMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_inx_proto protoreflect.FileDescriptor

var file_inx_proto_rawDesc = []byte{
	0x0a, 0x09, 0x69, 0x6e, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x69, 0x6e, 0x78,
	0x1a, 0x0e, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x0f, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x22, 0x45, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6e, 0x78,
	0x2e, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x35, 0x0a, 0x15, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22,
	0x5e, 0x0a, 0x0f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x8f, 0x01, 0x0a, 0x03, 0x49, 0x4e, 0x58, 0x12, 0x40, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x54, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x12, 0x2e, 0x69, 0x6e,
	0x78, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a,
	0x14, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x46, 0x0a, 0x0d, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x69, 0x6e, 0x78,
	0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x6f, 0x68, 0x6f, 0x72, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x78,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inx_proto_rawDescOnce sync.Once
	file_inx_proto_rawDescData = file_inx_proto_rawDesc
)

func file_inx_proto_rawDescGZIP() []byte {
	file_inx_proto_rawDescOnce.Do(func() {
		file_inx_proto_rawDescData = protoimpl.X.CompressGZIP(file_inx_proto_rawDescData)
	})
	return file_inx_proto_rawDescData
}

var file_inx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_inx_proto_goTypes = []interface{}{
	(*MessageFilter)(nil),         // 0: inx.MessageFilter
	(*SubmitMessageRequest)(nil),  // 1: inx.SubmitMessageRequest
	(*SubmitMessageResponse)(nil), // 2: inx.SubmitMessageResponse
	(*StreamedMessage)(nil),       // 3: inx.StreamedMessage
	(*WrappedMessage)(nil),        // 4: inx.WrappedMessage
}
var file_inx_proto_depIdxs = []int32{
	4, // 0: inx.SubmitMessageRequest.message:type_name -> inx.WrappedMessage
	4, // 1: inx.StreamedMessage.message:type_name -> inx.WrappedMessage
	0, // 2: inx.INX.ListenToMessages:input_type -> inx.MessageFilter
	1, // 3: inx.INX.SubmitMessage:input_type -> inx.SubmitMessageRequest
	3, // 4: inx.INX.ListenToMessages:output_type -> inx.StreamedMessage
	2, // 5: inx.INX.SubmitMessage:output_type -> inx.SubmitMessageResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inx_proto_init() }
func file_inx_proto_init() {
	if File_inx_proto != nil {
		return
	}
	file_wrappers_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_inx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inx_proto_goTypes,
		DependencyIndexes: file_inx_proto_depIdxs,
		MessageInfos:      file_inx_proto_msgTypes,
	}.Build()
	File_inx_proto = out.File
	file_inx_proto_rawDesc = nil
	file_inx_proto_goTypes = nil
	file_inx_proto_depIdxs = nil
}
