// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: wrappers.proto

package inx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WrappedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WrappedMessage) Reset() {
	*x = WrappedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wrappers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WrappedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrappedMessage) ProtoMessage() {}

func (x *WrappedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wrappers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrappedMessage.ProtoReflect.Descriptor instead.
func (*WrappedMessage) Descriptor() ([]byte, []int) {
	return file_wrappers_proto_rawDescGZIP(), []int{0}
}

func (x *WrappedMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_wrappers_proto protoreflect.FileDescriptor

var file_wrappers_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x69, 0x6e, 0x78, 0x22, 0x24, 0x0a, 0x0e, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x1d, 0x5a, 0x1b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x68, 0x6f, 0x72, 0x6e,
	0x65, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_wrappers_proto_rawDescOnce sync.Once
	file_wrappers_proto_rawDescData = file_wrappers_proto_rawDesc
)

func file_wrappers_proto_rawDescGZIP() []byte {
	file_wrappers_proto_rawDescOnce.Do(func() {
		file_wrappers_proto_rawDescData = protoimpl.X.CompressGZIP(file_wrappers_proto_rawDescData)
	})
	return file_wrappers_proto_rawDescData
}

var file_wrappers_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wrappers_proto_goTypes = []interface{}{
	(*WrappedMessage)(nil), // 0: inx.WrappedMessage
}
var file_wrappers_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wrappers_proto_init() }
func file_wrappers_proto_init() {
	if File_wrappers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wrappers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WrappedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wrappers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wrappers_proto_goTypes,
		DependencyIndexes: file_wrappers_proto_depIdxs,
		MessageInfos:      file_wrappers_proto_msgTypes,
	}.Build()
	File_wrappers_proto = out.File
	file_wrappers_proto_rawDesc = nil
	file_wrappers_proto_goTypes = nil
	file_wrappers_proto_depIdxs = nil
}
