#!/bin/bash
del /f /q /s "snapshots\alphanet1\full_export.bin"
del /f /q /s "snapshots\alphanet1\delta_export.bin"
del /f /q /s "snapshots\alphanet2\full_export.bin"
del /f /q /s "snapshots\alphanet2\delta_export.bin"
del /f /q /s "snapshots\alphanet3\full_export.bin"
del /f /q /s "snapshots\alphanet3\delta_export.bin"
del /f /q /s "snapshots\alphanet4\full_export.bin"
del /f /q /s "snapshots\alphanet4\delta_export.bin"
mkdir "snapshots\alphanet1\"
mkdir "snapshots\alphanet2\"
mkdir "snapshots\alphanet3\"
mkdir "snapshots\alphanet4\"
go run "..\main.go" tool snapgen alphanet1 60200bad8137a704216e84f8f9acfe65b972d9f4155becb4815282b03cef99fe 1000000000 "snapshots\alphanet1\full_export.bin"
copy "snapshots\alphanet1\full_export.bin" "snapshots\alphanet2\"
copy "snapshots\alphanet1\full_export.bin" "snapshots\alphanet3\"
copy "snapshots\alphanet1\full_export.bin" "snapshots\alphanet4\"
