package shutdown

const (
	PriorityCloseDatabase = iota
	PriorityFlushToDatabase
	PriorityRequestsProcessor
	PriorityTipselection
	PriorityMilestoneSolidifier
	PriorityMilestoneProcessor
	PrioritySolidifierGossip
	PriorityReceiveTxWorker
	PriorityMessageProcessor
	PriorityPeerGossipProtocolWrite
	PriorityPeerGossipProtocolRead
	PriorityGossipService
	PriorityBroadcastQueue
	PriorityKademliaDHT
	PriorityPeerDiscovery
	PriorityP2PManager
	PriorityHeartbeats
	PriorityWarpSync
	PrioritySnapshots
	PriorityMetricsUpdater
	PriorityDashboard
	PriorityPoWHandler
	PriorityRestAPI
	PriorityMetricsPublishers
	PrioritySpammer
	PriorityStatusReport
	PriorityMigrator
	PriorityCoordinator
	PriorityUpdateCheck
	PriorityPrometheus
)
