package shutdown

const (
	PriorityCloseDatabase = iota
	PriorityFlushToDatabase
	PriorityRequestsProcessor
	PriorityTipselection
	PriorityMilestoneSolidifier
	PriorityMilestoneProcessor
	PrioritySolidifierGossip
	PriorityReceiveTxWorker
	PriorityCurlHasher
	PriorityBroadcastQueue
	PriorityMessageProcessor
	PriorityPeerSendQueue
	PriorityPeeringTCPServer
	PriorityPeerReconnecter
	PriorityHeartbeats
	PriorityWarpSync
	PriorityLocalSnapshots
	PriorityMetricsUpdater
	PriorityDashboard
	PriorityPoWHandler
	PriorityAPI
	PriorityMetricsPublishers
	PrioritySpammer
	PriorityStatusReport
	PriorityAutopeering
	PriorityCoordinator
	PriorityUpdateCheck
	PriorityPrometheus
)
