{
 "title": "Node Dashboard",
 "description": "Dashboard for the IOTA node sofware",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "block_type",
    "query": {
     "query": "label_values(iota_gossip_node_block_count, type)"
    }
   },
   {
    "name": "peers",
    "query": {
     "query": "label_values(iota_gossip_peers_block_count, id)"
    }
   },
   {
    "name": "peer_block_type",
    "query": {
     "query": "label_values(iota_gossip_peers_block_count, type)"
    }
   },
   {
    "name": "peer_request_type",
    "query": {
     "query": "label_values(iota_gossip_peers_request_count, type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "description": "Node Version",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "iota_node_app_info", "legendFormat": "{{version}}" }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Uptime of the node",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(up{instance=\"hornet:9311\"}==1) by (instance)"
      }
     ]
    },
    {
     "title": "Synced",
     "type": "stat",
     "description": "The sync stat of the Node",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(iota_node_milestones{type=\"latest\"} - on () iota_node_milestones{type=\"confirmed\"})"
      }
     ]
    },
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "iota_node_health" }
     ]
    },
    {
     "title": "BPS",
     "type": "stat",
     "description": "Blocks and referenced blocks per second",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "iota_node_blocks_per_second", "legendFormat": "BPS" },
      {
       "expr": "iota_node_referenced_blocks_per_second",
       "legendFormat": "RBPS"
      }
     ]
    },
    {
     "title": "Ratio RBPS to BPS",
     "type": "stat",
     "description": "Ratio of referenced blocks in relation to new blocks of the last confirmed milestone.",
     "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "iota_node_referenced_rate" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "description": "CPU usage",
     "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"iota-node\"}[30s]) * 100"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "stat",
     "description": "RAM usage",
     "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(go_memstats_heap_inuse_bytes{job=\"iota-node\"} + (go_memstats_heap_idle_bytes{job=\"iota-node\"} - go_memstats_heap_released_bytes{job=\"iota-node\"}) + go_memstats_mspan_inuse_bytes{job=\"iota-node\"} + go_memstats_mcache_inuse_bytes{job=\"iota-node\"} + go_memstats_stack_sys_bytes{job=\"iota-node\"})"
      }
     ]
    },
    {
     "title": "Database Size",
     "type": "stat",
     "description": "Size of the ledger database",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "iota_database_utxo_size_bytes" }
     ]
    },
    {
     "title": "Neighbors",
     "type": "stat",
     "description": "Neighbors count",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(iota_gossip_peers_connected_count)"
      }
     ]
    },
    {
     "title": "Current",
     "type": "gauge",
     "description": "Current MPS",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "BPS" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "iota_node_blocks_per_second" }
     ]
    },
    {
     "type": "stat",
     "description": "MPS in the last 10 minutes",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "BPS" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(avg_over_time(iota_node_blocks_per_second[10m]))"
      }
     ]
    },
    {
     "type": "stat",
     "description": "MPS in the last day",
     "gridPos": { "h": 6, "w": 9, "x": 7, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "BPS" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(avg_over_time(iota_node_blocks_per_second[1d]))"
      }
     ]
    },
    {
     "title": "Milestones",
     "type": "stat",
     "description": "Milestone stats",
     "gridPos": { "h": 6, "w": 5, "x": 16, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "iota_node_milestones", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "Is compacting/pruning",
     "type": "stat",
     "description": "Pruning and compaction status",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "iota_database_pruning_running", "legendFormat": "Compacting" },
      { "expr": "iota_database_pruning_running", "legendFormat": "Pruning" }
     ]
    },
    {
     "type": "stat",
     "description": "MPS in the last hour",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "BPS" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(avg_over_time(iota_node_blocks_per_second[1h]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "iota_node_blocks_per_second", "legendFormat": "BPS" }
     ]
    },
    {
     "title": "Requests Per Second",
     "type": "graph",
     "description": "Requests Per second per type",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(iota_gossip_peers_request_count{type=~\"$peer_request_type\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Heartbeats Per Second",
     "type": "stat",
     "description": "Heartbeats per second",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(iota_gossip_node_heartbeat_count[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Sent Heartbeats Per Peer",
     "type": "piechart",
     "description": "Distribution of sent heartbeats per peer",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iota_gossip_peers_heartbeat_count{type=\"sent\"}"
      }
     ]
    },
    {
     "title": "Received Heartbeats Per Peer",
     "type": "piechart",
     "description": "Distribution of received heartbeats per peer",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iota_gossip_peers_heartbeat_count{type=\"received\"}"
      }
     ]
    },
    {
     "title": "Dropped Packages",
     "type": "stat",
     "description": "Sum of dropped packages",
     "gridPos": { "h": 8, "w": 4, "x": 15, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "iota_gossip_node_dropped_count" }
     ]
    },
    {
     "title": "Dropped Packages Per Peer",
     "type": "piechart",
     "description": "Distribution of dropped packages per peer",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iota_gossip_peers_dropped_count"
      }
     ]
    },
    {
     "title": "Blocks Per Second Per Peer",
     "type": "graph",
     "description": "BPS per peer per type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(iota_gossip_peers_block_count{type=~\"$peer_block_type\", id=~\"$peers\"}[1m])",
       "legendFormat": "{{id}} - {{type}}"
      }
     ]
    },
    {
     "title": "Requests Per Second Per Peer",
     "type": "graph",
     "description": "Requests per second per peer",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(iota_gossip_peers_request_count{type=~\"$peer_request_type\", id=~\"$peers\"}[1m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Caches Size",
     "type": "graph",
     "description": "Cache sizes per type",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "iota_caches_size", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "Database size",
     "type": "graph",
     "description": "Size of the Ledger database",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "iota_database_tangle_size_bytes",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compaction/Pruning Counts",
     "type": "stat",
     "description": "Compaction and Pruning Counts",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iota_database_tangle_compaction_count",
       "legendFormat": "Compaction"
      },
      { "expr": "iota_database_pruning_count", "legendFormat": "Pruning" }
     ]
    }
   ]
  },
  {
   "title": "Migrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receipts Metrics",
     "type": "stat",
     "description": "Stats for the migration receipts",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "iota_migrator_receipt_count", "legendFormat": "Receipt Count" },
      {
       "expr": "iota_migrator_receipt_entries_applied_count",
       "legendFormat": "Receipt Entries Applied Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Additional Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tips",
     "type": "graph",
     "description": "Amount of tips per second",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rate(iota_node_tip_count[5m])", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "Messages To Request",
     "type": "graph",
     "description": "Messages to request per second",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(iota_node_request_count[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Http Request Errors",
     "type": "stat",
     "description": "Http request errors",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iota_restapi_http_request_error_count"
      }
     ]
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Handled",
   "type": "timeseries",
   "description": "Total number of RPCs completed on the server, regardless of success or failure",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "grpc_server_handled_total",
     "legendFormat": "{{grpc_code}} - {{grpc_method}}"
    }
   ]
  }
 ]
}