name: Build Docker
on:
  push:
    paths:
      - "docker/Dockerfile"
      - "docker-compose.yml"
  pull_request:
    paths:
      - "docker/Dockerfile"
      - "docker-compose.yml"

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build HORNET Docker image
        run: docker build . --file docker/Dockerfile --tag hornet:latest

      - name: Test HORNET Docker image
        run: docker run --rm --name hornet hornet:latest --version 2>/dev/null | grep -q "HORNET"
