name: Test Docker image with Snyk

on:
  # Run this check every day at 03:00 to find potential new vulnerabilities in the develop branch
  schedule:
    - cron: "0 3 * * *"

jobs:
  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Build HORNET Docker image
        run: docker build . --file Dockerfile --tag hornet:latest

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@0.3.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: hornet:latest
          args: --org=gohornet --file=Dockerfile --exclude-app-vulns

      - name: Upload results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
          category: snyk-docker
